services:
  # SERVICIO 1: La Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: seniamaps-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - seniamaps-net

  # SERVICIO 2: Vuestra aplicación Spring Boot
  web:
    build: ./backend
    container_name: seniamaps-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Modificamos la URL de conexión para que apunte al nombre del servicio "db" en lugar de "localhost"
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/seniamaps?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_USER_PASSWORD}
    depends_on:
      - db
    networks:
      - seniamaps-net
  nginx:
    image: nginx:latest
    container_name: seniamaps-nginx
    restart: always

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    depends_on:
      - web

    networks:
      - seniamaps-net

  certbot:
    image: certbot/certbot
    container_name: seniamaps-certbot

    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

    networks:
      - seniamaps-net

volumes:
  mysql_data:

networks:
  seniamaps-net: